### ISSUE TITLE
Icons not visible on my QHD monitor (2560 x 1440)

### ISSUE THREAD

**Issue by xd003** [MakD/zombie-release#1]
As implied from the title, the icons throughtout jellyfin media player on my QHD monitor appear to be broken. Although the theme appears to be fine when jellyfin web is viewed on the browser. Also i would like to point out that the icons appear a bit too large than ideal in browser , ideally that could be fixed as well.

Screenshot from browser
![image](https://github.com/stpnwf/ZestyTheme/assets/26503185/d785d3da-9c74-4eec-8bc5-178cde34cf75)

Screenshots from jellyfin media player
![image](https://github.com/stpnwf/ZestyTheme/assets/26503185/cd708ce4-5c37-49ee-8df9-9e657647a90b)

![image](https://github.com/stpnwf/ZestyTheme/assets/26503185/543ee063-c927-4a7e-94c8-d8b2aabe75d6)

**Comment by MakD** [comment]
> As implied from the title, the icons throughtout jellyfin media player on my QHD monitor appear to be broken. Although the theme appears to be fine when jellyfin web is viewed on the browser. Also i would like to point out that the icons appear a bit too large than ideal in browser , ideally that could be fixed as well.
> 
> Screenshot from browser
> ![image](https://github.com/stpnwf/ZestyTheme/assets/26503185/d785d3da-9c74-4eec-8bc5-178cde34cf75)
> 
> Screenshots from jellyfin media player
> ![image](https://github.com/stpnwf/ZestyTheme/assets/26503185/cd708ce4-5c37-49ee-8df9-9e657647a90b)
> 
> ![image](https://github.com/stpnwf/ZestyTheme/assets/26503185/543ee063-c927-4a7e-94c8-d8b2aabe75d6)
> 

Do you have your "force enable web client enabled". If not can you try and check after enabling it.

**Comment by xd003** [comment]
I ticked the option which said - Force external web client in client settings. The icons are still broken

**Comment by MakD** [comment]
> I ticked the option which said - "Force external web client"  in client settings. The icons are still broken

Strange. It's working on my end with the icons being pulled normally. You are using which release? Your import url should say that

**Comment by xd003** [comment]
> Strange. It's working on my end with the icons being pulled normally. You are using which release? Your import url should say that.

Here's my whole custom css
```
@import url('https://cdn.jsdelivr.net/gh/MakD/zombie-release@latest/zombie-min-git.css');
@import url('https://cdn.jsdelivr.net/gh/stpnwf/ZestyTheme@latest/colorschemes/green.css');

/*if the logo is present on the details page and loaded hide the title so it doesnt duplicate and look weird*/
#itemDetailPage .itemName.infoText.parentNameLast > bdi:nth-child(1) {display: none;}
.hide+.detailPageWrapperContainer .itemName > bdi:nth-child(1) {display: block !important;}
/*the same but for the single episodes link back title*/
#itemDetailPage .parentName > bdi:nth-child(1) {display: none;}
.hide+.parentName > bdi:nth-child(1) {display: block !important;}
```

**Comment by xd003** [comment]
Even with a custom icon pack imported directly, jmp is still having problems rendering them. Lemme reinstall jmp and see how it goes

**Comment by xd003** [comment]
Update - still didn't help. i am gonna try a different windows machine and see how it goes there. On another note, don't you think removing the white borders around items in the navbar ( home/favourites) and on the top right would be a better thing to do. I have had all my users like this theme quite a lot except just that border

**Comment by MakD** [comment]
> Update - still didn't help. i am gonna try a different windows machine and see how it goes there. On another note, don't you think removing the white borders around items in the navbar ( home/favourites) and on the top right would be a better thing to do. I have had all my users like this theme quite a lot except just that border
> 
> Will also get my other friends to test this out on their systems as well to help pinpoint what might be causing it

Sure that will help.

Btw for the input, you can remove the border by adding this to your custom CSS

`.headerRight, .headerTabs {
    border-width: 0px !important;
}`

**Comment by xd003** [comment]
i am not sure how but randomly the icons started appearing fine inside jmp, i don't face the issue anymore
