### ISSUE TITLE
Mobile view is showing a bit of misalignment

### ISSUE THREAD

**Issue by hackmonker** [MakD/zombie-release#2]
![WhatsApp Image 2024-06-07 at 20 12 45_819495cd](https://github.com/MakD/zombie-release/assets/46002790/7368a084-98a1-490e-9196-d7ec3b153dcb)

I thought all the icons would be on the same line. anyway to fix this?

**Comment by MakD** [comment]
Can you try the latest release. The cdn might take some time to reflect, you can try force pulling by changing the @latest to @v10 in your import url.

**Comment by hackmonker** [comment]
yeah the new update fixed the alignment issue. thanks for the quick fix.

**Comment by MakD** [comment]
Great to hear that. Closing the issue👍
