### ISSUE TITLE
nextup in tv-show detail page alignment is too low

### ISSUE THREAD

**Issue by botus99** [MakD/zombie-release#3]
### Description

When clicking on a tv show with an episode in the '.nextUpSection' popup, the margins are set low enough to get covered up by season posters (if there are enough seasons, 6 or 7 IIRC).

### Steps to Reproduce

1. Find a tv show with episodes labeled for 'Up Next' that has more than 6 seasons
2. Click/enter the detail page for the tv show
3. Observe the bottom of the .nextUpSection popup being cut off

### Expected Behavior

The alignment of .nextUpSection to be a little higher to compensate for season posters

### Actual Behavior

The bottom of .nextUpSection gets obscured by season posters

---

### My "solution"

I played around with the css and adjusted the margins and padding starting on line 1403...
```
.layout-desktop .nextUpSection {
  border-radius: 34px;
  margin: -5.5vh 2.5em 1vh 66%;
  padding-left: 2.5em;
  padding-right: 1.5em;
  padding-top: 0.0em;
  background-color: rgba(var(--darkest), 0.8);
  backdrop-filter: blur(4px);
  position: absolute;
}
```

I'm no css expert or design guru though. The changes appear to fix the alignment issue on my end though! 

Thanks for the hard work and a great theme!

**Comment by MakD** [comment]
@botus99 I just pushed a fix. That should be solved now

**Comment by botus99** [comment]
Good stuff, friend. Thanks for the quick updates!
