### ISSUE TITLE
Checkbox Icons are not centered

### ISSUE THREAD

**Issue by IceToast** [MakD/zombie-release#4]
I just noticed the checkbox icons are not centered within the checkbox:
The only CSS applied is the main css.

![image](https://github.com/MakD/zombie-release/assets/54889359/16c92396-76a7-4114-82bc-0c8742ef64a7)

**Comment by IceToast** [comment]
Same goes for forward/backward icons when hovered:
![image](https://github.com/MakD/zombie-release/assets/54889359/3e382ad0-0147-49fc-9ad9-0cd63aa78009)

**Comment by MakD** [comment]
@IceToast this is due to the custom icons the css is using

**Comment by IceToast** [comment]
The soltion is to add a justify-content css param to the .material-icons class:

```css
.material-icons {
    justify-content: center;
}
```

**Comment by MakD** [comment]
Thanks @IceToast will add this to the next release. Closing this for now.
