### ISSUE TITLE
menu is above the text

### ISSUE THREAD

**Issue by Blackspirits** [MakD/zombie-release#5]
menu is above the text

![Jellyfin](https://github.com/MakD/zombie-release/assets/11444904/37d73cc3-3e28-404c-b765-78471d8ab8c1)

**Comment by MakD** [comment]
> menu is above the text
> 
> ![Jellyfin](https://github.com/MakD/zombie-release/assets/11444904/37d73cc3-3e28-404c-b765-78471d8ab8c1)
> 

Can you try updating to the latest jellyfin release. Cannot reproduce the same on my end

**Comment by Blackspirits** [comment]
Thanks, the update fixed it. I don't know how I didn't remember to update. Thank you very much
