### ISSUE TITLE
Featured/ Slideshow 

### ISSUE THREAD

**Issue by Akouniza** [MakD/zombie-release#7]
Hello,

I just set up your theme and it's looking really great, but I'm facing an issue, I'm having a blank slideshow like in the screenshot. 
[Capture d'écran 2024-07-20 190211](https://github.com/user-attachments/assets/c0803a78-f106-4dc8-bd01-7605f614ff79)

I did exactly the same as you mentioned (stopped jellyfin before anything), tried to add some movies/tv shows on favorite or populate list.txt with links but no avails.

Best Regards,
Akou

**Comment by MakD** [comment]
can you try removing the list.txt. it should generate random picks from your library

**Comment by MakD** [comment]
Are you also on Linux.and.docker

**Comment by Akouniza** [comment]
Im on Linux, not on docker

**Comment by Akouniza** [comment]
I’m gonna try the new version you uploaded soon :)

**Comment by Akouniza** [comment]
So i'm using the latest version and still the same issue, i'm using this path `/usrs/share/jellyfin/web/avatars`, could that be the reason?

**Comment by MakD** [comment]
Can you post your issues in the actual forum for this featured bar? I am
not a docker user, so I am unable to replicate it on my end.

Link for the thread -
https://forum.jellyfin.org/t-featured-content-bar?page=5

**Comment by Akouniza** [comment]
I would like to but i'm not using docker at all for this install, it's a Linux VM under Proxmox Hypervisor VM

**Comment by MakD** [comment]
> So i'm using the latest version and still the same issue, i'm using this path `/usrs/share/jellyfin/web/avatars`, could that be the reason?

Jellyfin has read permissions right.?

**Comment by BobHasNoSoul** [comment]
if you still need help.... im able to help out if you have discord i can help you out way easier after (around work that is) 

slight update (for some reason my jellyfin forum account is either banned.. blocked.. or login and reset are just magically not loading on my end. hence its easier on discord or here just send me a tag on here @Akouniza

**Comment by MakD** [comment]
@BobHasNoSoul can you share your discord details for a connect

**Comment by Akouniza** [comment]
> if you still need help.... im able to help out if you have discord i can help you out way easier after (around work that is) 
> 
> 
> 
> slight update (for some reason my jellyfin forum account is either banned.. blocked.. or login and reset are just magically not loading on my end. hence its easier on discord or here just send me a tag on here @Akouniza 

Hey! 

Thanks I would be more than happy, but don't stress it's not a hurry.

Here's my discord: .akou
I'll delete my message after your invite. 

If we manage to diagnose the issue I'll open a new issue and share everything we had so far.

Akou

**Comment by BobHasNoSoul** [comment]
Added you :)

**Comment by BobHasNoSoul** [comment]
> @BobHasNoSoul can you share your discord details for a connect

Let me know when you add me, I use many names online and tend to keep them separate to stop cross talk.. I will redact it when you add me 

gamerinamask93

**Comment by MakD** [comment]
> > @BobHasNoSoul can you share your discord details for a connect
> 
> Let me know when you add me, I use many names online and tend to keep them separate to stop cross talk.. I will redact it when you add me 
> 
> gamerinamask93

Sent. You will see a request from M0RPHi
